/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";

export interface AllAccounts extends TpastreamApi.commons.Pageable {
  data: TpastreamApi.employers.Account;
}
