/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface AllAccounts extends TpaStreamApi.commons.Pageable {
  data: TpaStreamApi.employers.Account;
}
