/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AllAccounts: core.schemas.ObjectSchema<AllAccounts.Raw, TpastreamApi.employers.AllAccounts> = core.schemas
  .object({
    data: core.schemas.lazyObject(() => schemas.employers.Account),
  })
  .extend(core.schemas.lazyObject(() => schemas.commons.Pageable));

export declare namespace AllAccounts {
  interface Raw extends schemas.commons.Pageable.Raw {
    data: schemas.employers.Account.Raw;
  }
}
