/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AllMembers: core.schemas.ObjectSchema<AllMembers.Raw, TpaStreamApi.member.AllMembers> = core.schemas
  .object({
    data: core.schemas.lazyObject(() => schemas.member.Member),
  })
  .extend(core.schemas.lazyObject(() => schemas.commons.Pageable));

export declare namespace AllMembers {
  interface Raw extends schemas.commons.Pageable.Raw {
    data: schemas.member.Member.Raw;
  }
}
