/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../../../core";
import { TpaStreamApi } from "../../..";
import urlJoin from "url-join";
import * as schemas from "../../../schemas";

export interface Client {
  get_(): Promise<TpaStreamApi.key.get_.Response>;
  create(request: string): Promise<TpaStreamApi.key.create.Response>;
  deleteKey(request: TpaStreamApi.key.deleteKey.Request): Promise<TpaStreamApi.key.deleteKey.Response>;
}

export declare namespace Client {
  interface Options {
    _origin: string;
    _credentials?: core.Supplier<core.BasicAuth>;
  }
}

export class Client implements Client {
  constructor(private readonly options: Client.Options) {}

  public async get_(): Promise<TpaStreamApi.key.get_.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/public_key/gpg/"),
      method: "GET",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options._credentials)),
      },
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.key.PublicKey.parse(response.body as schemas.key.PublicKey.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async create(request: string): Promise<TpaStreamApi.key.create.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/public_key/gpg/"),
      method: "POST",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options._credentials)),
      },
      body: schemas.key.create.Request.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.key.PublicKey.parse(response.body as schemas.key.PublicKey.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async deleteKey(request: TpaStreamApi.key.deleteKey.Request): Promise<TpaStreamApi.key.deleteKey.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, `/public_key/gpg/${request.name}`),
      method: "DELETE",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options._credentials)),
      },
    });
    if (response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
