/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const MemberResponse: core.schemas.ObjectSchema<MemberResponse.Raw, TpaStreamApi.member.MemberResponse> =
  core.schemas.object({
    data: core.schemas.lazyObject(() => serializers.member.Member),
  });

export declare namespace MemberResponse {
  interface Raw {
    data: serializers.member.Member.Raw;
  }
}
