/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";

export const PublicKey: core.schemas.ObjectSchema<PublicKey.Raw, TpastreamApi.key.PublicKey> = core.schemas.object({
  content: core.schemas.string(),
  expires: core.schemas.string(),
  name: core.schemas.string(),
  uuid: core.schemas.string(),
});

export declare namespace PublicKey {
  interface Raw {
    content: string;
    expires: string;
    name: string;
    uuid: string;
  }
}
