/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../../../core";
import { TpastreamApi } from "../../..";
import urlJoin from "url-join";
import * as schemas from "../../../schemas";

export interface Client {
  getAll(request: TpastreamApi.claims.getAll.Request): Promise<TpastreamApi.claims.getAll.Response>;
}

export declare namespace Client {
  interface Options {
    _origin: string;
    _token?: core.Supplier<core.BearerToken>;
  }
}

export class Client implements Client {
  constructor(private readonly options: Client.Options) {}

  public async getAll(request: TpastreamApi.claims.getAll.Request): Promise<TpastreamApi.claims.getAll.Response> {
    const queryParameters = new URLSearchParams();
    if (request.page != null) {
      queryParameters.append("page", request.page.toString());
    }

    if (request.perPage != null) {
      queryParameters.append("per_page", request.perPage.toString());
    }

    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/claims/"),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options._token)),
      },
      queryParameters: queryParameters,
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.claims.AllClaims.parse(response.body as schemas.claims.AllClaims.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
