/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";

export interface AllClaims extends TpastreamApi.commons.Pageable {
  data: TpastreamApi.claims.Claim;
}
