/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface Claim {
  /** Use computed_amount_allowed in case this field is missing. */
  amountAllowed: number;
  /** Use computed_amount_billed in case this field is missing. */
  amountBilled: number;
  /** Use computed_amount_not_covered in case this field is missing. */
  amountNotCovered: number;
}
