/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";

export interface Member {
  email?: string;
  employer: TpastreamApi.claims.Employer;
  firstName?: string;
  id: number;
  lastName?: string;
  systemKey: Record<string, string>;
}
