/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface Account {
  accounts: TpaStreamApi.employer.Accounts;
  address?: string;
  alegeusKey?: string;
  archived: boolean;
  archivedDate: Date;
  archivedby: string;
  canMakeClaimRequests?: boolean;
}
