/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface Dependent {
  address?: string;
  alegeusKey?: string;
  createddate: Date;
  dateOfBirth?: string;
  email?: string;
  firstName?: string;
  gender?: string;
  id?: number;
  lastName: string;
  middleName: string;
  modifieddate: Date;
  ssn?: string;
}
