/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface Employer1 {
  archived?: boolean;
  eligiblePayers?: TpaStreamApi.employer.Payer[];
  emailAutomation?: boolean;
  employerId?: number;
  id?: number;
  name: string;
  payers: TpaStreamApi.employer.Payer1[];
  slug?: string;
  supportEmailDerived?: string;
  supportPhoneDerived?: string;
  supportLogoDerived?: string;
  supportNameDerived?: string;
}
