/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface MemberPagination extends TpaStreamApi.commons.Pageable {
  data: TpaStreamApi.employer.Member;
}
