/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface Member1 {
  accounts?: TpaStreamApi.employer.Account[];
  address?: string;
  alegeusKey?: string;
  archived?: boolean;
  archivedDate?: Date;
  archivedby?: TpaStreamApi.employer.ArchivedBy;
  canMakeClaimRequests?: boolean;
  canUsePortal?: boolean;
  createddate?: Date;
  dateOfBirth?: string;
  dependents?: TpaStreamApi.employer.Dependent[];
  email?: string;
  employer?: TpaStreamApi.employer.Employer;
  firstName?: string;
  firstNameDerived?: string;
  fullNameDerived?: string;
  gender?: string;
  hireTermDaterange?: TpaStreamApi.employer.HireTermDaterange;
  id?: number;
  lastName?: string;
  lastNameDerived?: string;
  modifieddate?: Date;
  phoneHome?: string;
  phoneMobile?: string;
  ssn?: string;
  tenant?: TpaStreamApi.employer.Tenant;
  unreadCount?: number;
  vendorMembers: TpaStreamApi.employer.VendorMember[];
}
