/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface Tenant {
  alegeusKeyEnabled?: boolean;
  id?: number;
  name: string;
  tenantId: number;
  vendorTenants: TpaStreamApi.employer.VendorTenant1;
}
