/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface VendorMember {
  key: string;
  vendorTenant: TpaStreamApi.employer.VendorTenant;
}
