/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface VendorTenant1 {
  id?: number;
  keyEnabled?: boolean;
  label?: string;
  vendor?: TpaStreamApi.employer.Vendor;
}
