/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Accounts: core.schemas.ObjectSchema<Accounts.Raw, TpaStreamApi.employer.Accounts> = core.schemas.object({
  id: core.schemas.number(),
  name: core.schemas.string(),
});

export declare namespace Accounts {
  interface Raw {
    id: number;
    name: string;
  }
}
