/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface AllMembers extends TpaStreamApi.commons.Pageable {
  data: TpaStreamApi.member.Member;
}
