/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const ClaimTypeName: core.schemas.Schema<ClaimTypeName.Raw, TpaStreamApi.claim.ClaimTypeName> = core.schemas
  .string()
  .transform<TpaStreamApi.claim.ClaimTypeName>({
    parse: (value) => TpaStreamApi.claim.ClaimTypeName._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ClaimTypeName {
  type Raw = string;
}
