/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";

export interface ClaimLine {
  amountAllowed?: number;
  amountBilled?: number;
  amountNotCovered?: number;
  amountPaid?: number;
  amountPaidOther?: number;
  coinsurancePatient?: number;
  copayment?: number;
  dateOfService: TpaStreamApi.claim.DateRange;
  daysSupply?: number;
  diagnosisCode?: string;
  discount?: number;
  id?: number;
  nationalDrugCode?: string;
  patientResponsibility?: number;
  prescriptionTypeId?: number;
  prescriptionTypeStr?: string;
  procedureCode?: string;
  procedureName?: string;
  quantity?: number;
  reduction?: number;
  totalPatientResponsibility?: number;
  uuid?: string;
  vendorSystemId?: string;
}
