/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AllClaims: core.schemas.ObjectSchema<AllClaims.Raw, TpastreamApi.claims.AllClaims> = core.schemas.object({
  data: core.schemas.lazy(() => schemas.claims.AllClaimsData),
});

export declare namespace AllClaims {
  interface Raw {
    data: schemas.claims.AllClaimsData.Raw;
  }
}
