/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";

export const ClaimTypeId: core.schemas.Schema<ClaimTypeId.Raw, TpastreamApi.claims.ClaimTypeId> = core.schemas
  .string()
  .transform<TpastreamApi.claims.ClaimTypeId>({
    parse: (value) => TpastreamApi.claims.ClaimTypeId._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ClaimTypeId {
  type Raw = string;
}
