/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";

export const ClaimTypeName: core.schemas.Schema<ClaimTypeName.Raw, TpastreamApi.claims.ClaimTypeName> = core.schemas
  .string()
  .transform<TpastreamApi.claims.ClaimTypeName>({
    parse: (value) => TpastreamApi.claims.ClaimTypeName._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ClaimTypeName {
  type Raw = string;
}
