/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ClaimLine: core.schemas.ObjectSchema<ClaimLine.Raw, TpaStreamApi.claims.ClaimLine> = core.schemas.object({
  amountAllowed: core.schemas.property("amount_allowed", core.schemas.number().optional()),
  amountBilled: core.schemas.property("amount_billed", core.schemas.number().optional()),
  amountNotCovered: core.schemas.property("amount_not_covered", core.schemas.number().optional()),
  amountPaid: core.schemas.property("amount_paid", core.schemas.number().optional()),
  amountPaidOther: core.schemas.property("amount_paid_other", core.schemas.number().optional()),
  coinsurancePatient: core.schemas.property("coinsurance_patient", core.schemas.number().optional()),
  copayment: core.schemas.number().optional(),
  dateOfService: core.schemas.property(
    "date_of_service",
    core.schemas.lazyObject(() => schemas.claims.DateRange)
  ),
  daysSupply: core.schemas.property("days_supply", core.schemas.number().optional()),
  diagnosisCode: core.schemas.property("diagnosis_code", core.schemas.string().optional()),
  discount: core.schemas.number().optional(),
  id: core.schemas.number().optional(),
  nationalDrugCode: core.schemas.property("national_drug_code", core.schemas.string().optional()),
  patientResponsibility: core.schemas.property("patient_responsibility", core.schemas.number().optional()),
  prescriptionTypeId: core.schemas.property("prescription_type_id", core.schemas.number().optional()),
  prescriptionTypeStr: core.schemas.property("prescription_type_str", core.schemas.string().optional()),
  procedureCode: core.schemas.property("procedure_code", core.schemas.string().optional()),
  procedureName: core.schemas.property("procedure_name", core.schemas.string().optional()),
  quantity: core.schemas.number().optional(),
  reduction: core.schemas.number().optional(),
  totalPatientResponsibility: core.schemas.property("total_patient_responsibility", core.schemas.number().optional()),
  uuid: core.schemas.string().optional(),
  vendorSystemId: core.schemas.property("vendor_system_id", core.schemas.string().optional()),
});

export declare namespace ClaimLine {
  interface Raw {
    amount_allowed?: number | null;
    amount_billed?: number | null;
    amount_not_covered?: number | null;
    amount_paid?: number | null;
    amount_paid_other?: number | null;
    coinsurance_patient?: number | null;
    copayment?: number | null;
    date_of_service: schemas.claims.DateRange.Raw;
    days_supply?: number | null;
    diagnosis_code?: string | null;
    discount?: number | null;
    id?: number | null;
    national_drug_code?: string | null;
    patient_responsibility?: number | null;
    prescription_type_id?: number | null;
    prescription_type_str?: string | null;
    procedure_code?: string | null;
    procedure_name?: string | null;
    quantity?: number | null;
    reduction?: number | null;
    total_patient_responsibility?: number | null;
    uuid?: string | null;
    vendor_system_id?: string | null;
  }
}
