/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";

export const Claim: core.schemas.ObjectSchema<Claim.Raw, TpastreamApi.claims.Claim> = core.schemas.object({
  amountAllowed: core.schemas.property("amount_allowed", core.schemas.number()),
  amountBilled: core.schemas.property("amount_billed", core.schemas.number()),
  amountNotCovered: core.schemas.property("amount_not_covered", core.schemas.number()),
});

export declare namespace Claim {
  interface Raw {
    amount_allowed: number;
    amount_billed: number;
    amount_not_covered: number;
  }
}
