/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ClaimType: core.schemas.ObjectSchema<ClaimType.Raw, TpaStreamApi.claims.ClaimType> = core.schemas.object({
  name: core.schemas.lazy(() => schemas.claims.ClaimTypeName),
});

export declare namespace ClaimType {
  interface Raw {
    name: schemas.claims.ClaimTypeName.Raw;
  }
}
