/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const DateRange: core.schemas.ObjectSchema<DateRange.Raw, TpaStreamApi.claims.DateRange> = core.schemas.object({
  bounds: core.schemas.string().optional(),
  end: core.schemas.string().optional(),
  start: core.schemas.string().optional(),
});

export declare namespace DateRange {
  interface Raw {
    bounds?: string | null;
    end?: string | null;
    start?: string | null;
  }
}
