/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpastreamApi } from "../../..";
import * as core from "../../../core";

export const Employer: core.schemas.ObjectSchema<Employer.Raw, TpastreamApi.claims.Employer> = core.schemas.object({
  id: core.schemas.number().optional(),
  name: core.schemas.string().optional(),
  reimbursementPolicy: core.schemas.property("reimbursement_policy", core.schemas.unknown()),
});

export declare namespace Employer {
  interface Raw {
    id?: number | null;
    name?: string | null;
    reimbursement_policy?: unknown;
  }
}
