/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Network: core.schemas.Schema<Network.Raw, TpaStreamApi.claims.Network> = core.schemas
  .string()
  .transform<TpaStreamApi.claims.Network>({
    parse: (value) => TpaStreamApi.claims.Network._parse(value),
    json: ({ value }) => value,
  });

export declare namespace Network {
  type Raw = string;
}
