/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const PolicyHolder: core.schemas.ObjectSchema<PolicyHolder.Raw, TpaStreamApi.claims.PolicyHolder> =
  core.schemas.object({
    firstName: core.schemas.property("first_name", core.schemas.string().optional()),
    lastName: core.schemas.property("last_name", core.schemas.string().optional()),
    id: core.schemas.number(),
  });

export declare namespace PolicyHolder {
  interface Raw {
    first_name?: string | null;
    last_name?: string | null;
    id: number;
  }
}
