/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const AllClaims: core.schemas.ObjectSchema<AllClaims.Raw, TpaStreamApi.claim.AllClaims> = core.schemas
  .object({
    data: core.schemas.lazyObject(() => serializers.claim.Claim),
  })
  .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace AllClaims {
  interface Raw extends serializers.commons.Pageable.Raw {
    data: serializers.claim.Claim.Raw;
  }
}
