/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const ClaimTypeId: core.schemas.Schema<ClaimTypeId.Raw, TpaStreamApi.claim.ClaimTypeId> = core.schemas
  .string()
  .transform<TpaStreamApi.claim.ClaimTypeId>({
    parse: (value) => TpaStreamApi.claim.ClaimTypeId._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ClaimTypeId {
  type Raw = string;
}
