/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://app.tpastream.com/api/v2",
} as const;

export type Environment = typeof Environment.Production;
