/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Account: core.schemas.ObjectSchema<Account.Raw, TpaStreamApi.employer.Account> = core.schemas.object({
  id: core.schemas.number(),
  name: core.schemas.string(),
});

export declare namespace Account {
  interface Raw {
    id: number;
    name: string;
  }
}
