/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const ArchivedBy: core.schemas.ObjectSchema<ArchivedBy.Raw, TpaStreamApi.employer.ArchivedBy> =
  core.schemas.object({
    email: core.schemas.string().optional(),
    id: core.schemas.number().optional(),
  });

export declare namespace ArchivedBy {
  interface Raw {
    email?: string | null;
    id?: number | null;
  }
}
