/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Dependent: core.schemas.ObjectSchema<Dependent.Raw, TpaStreamApi.employer.Dependent> = core.schemas.object(
  {
    address: core.schemas.string().optional(),
    alegeusKey: core.schemas.property("alegeus_key", core.schemas.string().optional()),
    createddate: core.schemas.date(),
    dateOfBirth: core.schemas.property("date_of_birth", core.schemas.string().optional()),
    email: core.schemas.string().optional(),
    firstName: core.schemas.property("first_name", core.schemas.string().optional()),
    gender: core.schemas.string().optional(),
    id: core.schemas.number().optional(),
    lastName: core.schemas.property("last_name", core.schemas.string()),
    middleName: core.schemas.property("middle_name", core.schemas.string()),
    modifieddate: core.schemas.date(),
    ssn: core.schemas.string().optional(),
  }
);

export declare namespace Dependent {
  interface Raw {
    address?: string | null;
    alegeus_key?: string | null;
    createddate: string;
    date_of_birth?: string | null;
    email?: string | null;
    first_name?: string | null;
    gender?: string | null;
    id?: number | null;
    last_name: string;
    middle_name: string;
    modifieddate: string;
    ssn?: string | null;
  }
}
