/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const HireTermDaterange: core.schemas.ObjectSchema<
  HireTermDaterange.Raw,
  TpaStreamApi.employer.HireTermDaterange
> = core.schemas.object({
  bounds: core.schemas.string().optional(),
  end: core.schemas.string().optional(),
  start: core.schemas.string().optional(),
});

export declare namespace HireTermDaterange {
  interface Raw {
    bounds?: string | null;
    end?: string | null;
    start?: string | null;
  }
}
