/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Payer1: core.schemas.ObjectSchema<Payer1.Raw, TpaStreamApi.employer.Payer1> = core.schemas.object({
  id: core.schemas.number().optional(),
  name: core.schemas.string(),
  retriever: core.schemas.string(),
  shortName: core.schemas.property("short_name", core.schemas.string().optional()),
});

export declare namespace Payer1 {
  interface Raw {
    id?: number | null;
    name: string;
    retriever: string;
    short_name?: string | null;
  }
}
