/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const VendorMember: core.schemas.ObjectSchema<VendorMember.Raw, TpaStreamApi.employer.VendorMember> =
  core.schemas.object({
    key: core.schemas.string(),
    vendorTenant: core.schemas.property(
      "vendor_tenant",
      core.schemas.lazyObject(() => serializers.employer.VendorTenant)
    ),
  });

export declare namespace VendorMember {
  interface Raw {
    key: string;
    vendor_tenant: serializers.employer.VendorTenant.Raw;
  }
}
