/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";

export const Vendor: core.schemas.ObjectSchema<Vendor.Raw, TpaStreamApi.employer.Vendor> = core.schemas.object({
  code: core.schemas.string(),
  id: core.schemas.number().optional(),
  name: core.schemas.string(),
});

export declare namespace Vendor {
  interface Raw {
    code: string;
    id?: number | null;
    name: string;
  }
}
