/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const VendorTenant: core.schemas.ObjectSchema<VendorTenant.Raw, TpaStreamApi.employer.VendorTenant> =
  core.schemas.object({
    id: core.schemas.number().optional(),
    label: core.schemas.string().optional(),
    vendor: core.schemas.lazyObject(() => serializers.employer.Vendor).optional(),
  });

export declare namespace VendorTenant {
  interface Raw {
    id?: number | null;
    label?: string | null;
    vendor?: serializers.employer.Vendor.Raw | null;
  }
}
