/**
 * This file auto-generated by Fern from our API Definition.
 */

import { TpaStreamApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const VendorTenant1: core.schemas.ObjectSchema<VendorTenant1.Raw, TpaStreamApi.employer.VendorTenant1> =
  core.schemas.object({
    id: core.schemas.number().optional(),
    keyEnabled: core.schemas.property("key_enabled", core.schemas.boolean().optional()),
    label: core.schemas.string().optional(),
    vendor: core.schemas.lazyObject(() => serializers.employer.Vendor).optional(),
  });

export declare namespace VendorTenant1 {
  interface Raw {
    id?: number | null;
    key_enabled?: boolean | null;
    label?: string | null;
    vendor?: serializers.employer.Vendor.Raw | null;
  }
}
