/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../../../core";
import { TpaStreamApi } from "../../..";
import urlJoin from "url-join";
import * as schemas from "../../../schemas";

export interface Client {
  getAllMembers(
    request: TpaStreamApi.member.getAllMembers.Request
  ): Promise<TpaStreamApi.member.getAllMembers.Response>;
  getMember(request: TpaStreamApi.member.getMember.Request): Promise<TpaStreamApi.member.getMember.Response>;
}

export declare namespace Client {
  interface Options {
    _origin: string;
    _credentials?: core.Supplier<core.BasicAuth>;
  }
}

export class Client implements Client {
  constructor(private readonly options: Client.Options) {}

  public async getAllMembers(
    request: TpaStreamApi.member.getAllMembers.Request
  ): Promise<TpaStreamApi.member.getAllMembers.Response> {
    const queryParameters = new URLSearchParams();
    if (request.page != null) {
      queryParameters.append("page", request.page.toString());
    }

    if (request.perPage != null) {
      queryParameters.append("per_page", request.perPage.toString());
    }

    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/member/"),
      method: "GET",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options._credentials)),
      },
      queryParameters: queryParameters,
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.member.AllMembers.parse(response.body as schemas.member.AllMembers.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async getMember(
    request: TpaStreamApi.member.getMember.Request
  ): Promise<TpaStreamApi.member.getMember.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, `/member/${request.memberId}`),
      method: "POST",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options._credentials)),
      },
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.member.MemberResponse.parse(response.body as schemas.member.MemberResponse.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
