/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../core";
import { Client as ClaimsServiceClient } from "./claims/client/Client";

export namespace Client {
  export interface Options {
    _origin: string;
    _token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #claims: ClaimsServiceClient | undefined;

  public get claims(): ClaimsServiceClient {
    return (this.#claims ??= new ClaimsServiceClient({
      _origin: this.options._origin,
      _token: this.options._token,
    }));
  }
}
